### ISSUE TITLE
Maintenance: Publish documentation

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#152]
## Description of the improvement

**Summary of the proposal**

Publish first version of documentation for beta release

**How, where did you look for information**

N/A

**Missing or unclear documentation**

N/A

**Improvement**

 - [ ] Documentation Homepage [#250](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/250/)
 - [ ] Documentation for Logger [#130](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/130)
 - [ ] Documentation for Metrics [#151](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/151)
 - [ ] Documentation for Tracer [#153](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/153)
 - [ ] Automate publishing on GitHub Pages ⚠️ _Issue missing_ ⚠️

### Related existing documentation
https://awslabs.github.io/aws-lambda-powertools-python/

### Related issues, RFCs

[#130](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/130)
[#152](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/152)
[#153](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/153)
