### ISSUE TITLE
Feature request: feature parity with Python Powertools logger

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#482]
## Description of the feature request

As addressed in [this comment](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/293#issuecomment-992005781), we should revisit the current features of the Logger to make sure there is feature parity.

Some of the mentioned items are not listed as they are captured by another ticket.

- [x] Logging incoming event functionality
- [x] Custom keys are persisted across warm invocations
- [ ] `location` key in log structure
- [x] Removing log keys (#901)
- [x] Clearing all state (#902)
- [x] ~~Concept of logger name~~
- [x] ~~Correlation ID will be captured in #129 #139~~ 

**Problem statement**

The Logger utility has a number of functionalities shipped in 2021 that are currently not in TS.  

**Summary of the feature**

**For each functionality above:**
- [x] Evaluate if the feature should be ported (does it make sense for the TS ecosystem?) or can't be ported because of language's different behaviour

If it can and should be ported:

- Business logic
- Unit tests
- E2E tests
- Examples
- JsDocs (when applicable)
- Documentation

For this reason it's recommended that whoever picks this issue should create one separated PR for each checklist item.

**Code examples**

N/A

**Benefits for you and the wider AWS community**

Feature parity with the Python Powertool.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### Related issues, RFCs
N/A

**Comment by saragerion** [comment]
Note: the location logic will be discussed further and captured in another PR, as agreed with @flochaz and @dreamorosi
